apiVersion: v1
kind: Service
metadata:
  name: webapi-service
  labels:
    app: webapi-service
spec:
  ports:
    # the port that this service should serve on
    - port: 8000
      targetPort: 80
  selector:
    app: webapi-service
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: webapi-service
  name: webapi-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: webapi-service
  template:
    metadata:
      labels:
        app: webapi-service
      name: webapi-service
    spec:
     containers:
      - name: webapi-service
        image: garyr/service-app:1.0.0        
     nodeSelector:
      kubernetes.io/os: windows